### ISSUE TITLE
Error out better when a user doesn't have wkhtmltopdf installed

### ISSUE THREAD

**Issue by knennigtri** [knennigtri/merge-markdown#42]
merge-markdown requires wkhtmltopdf installed first: http://wkhtmltopdf.org/downloads.html
```
C:\Users\prpurush\AppData\Roaming\npm\node_modules\@knennigtri\merge-markdown\node_modules\wkhtmltopdf\index.js:180
    throw new Error(err); // critical error
    ^
Error: Error: spawn wkhtmltopdf ENOENT
    at ChildProcess.<anonymous> (C:\Users\prpurush\AppData\Roaming\npm\node_modules\@knennigtri\merge-markdown\node_modules\wkhtmltopdf\index.js:180:11)
    at Object.onceWrapper (events.js:520:26)
    at ChildProcess.emit (events.js:400:28)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

**Comment by knennigtri** [comment]
https://stackoverflow.com/questions/29007515/error-when-using-wkhtmltopdf

**Comment by knennigtri** [comment]
ba8f78c6940ee24544ad7880fb464440e2b93cca
